export const allCities = [
    "Minas Tirith",
    "Agar",
    "Aldburg",
    "Almaida",
    "Alqualondë",
    "Andúnië",
    "Annúminas",
    "Archet",
    "Armenelos",
    "Avallónë",
    "Bablon",
    "Belegost",
    "Bree",
    "Breredon",
    "Brithombar",
    "Bucklebury",
    "Calembel",
    "Caras Galadhon",
    "Carn Dûm",
    "Celbaros",
    "Combe",
    "Crickhollow",
    "Dáin's hall",
    "Dale",
    "Dol Amroth",
    "Edhellond",
    "Edoras",
    "Eglarest",
    "Elvenking's Halls",
    "Ephel Brandir",
    "Estirin",
    "Forgotten Villages",
    "Forlond",
    "Fornost Erain",
    "Framsburg",
    "Goblin-town",
    "Gondolin",
    "Grey Havens",
    "Harlond (Gondor)",
    "Harlond (Lindon)",
    "Havens of Círdan",
    "Havens of the Falas",
    "Haysend",
    "Kingdom under the Mountain",
    "Kortirion",
    "Lake-town",
    "Linhir",
    "Lond Daer",
    "Menegroth",
    "Minas Anor",
    "Minas Ithil",
    "Minas Morgul",
    "Moria",
    "Mundburg",
    "Nargothrond",
    "Newbury",
    "Nindamos",
    "Ninwi",
    "Nogrod",
    "Nulukkizdîn",
    "Ondosto",
    "Osgiliath",
    "Ost-in-Edhil",
    "Pelargir",
    "Rivendell",
    "Rómenna",
    "Rûm",
    "Staddle",
    "Standelf",
    "Taruithorn",
    "Tavrobel",
    "Tharbad",
    "Tirion",
    "Trui",
    "Udul",
    "Umbar",
    "Underharrow",
    "Upbourn",
    "Valmar",
    "Vinyalondë",
    "Vinyamar",
    "Budgeford",
    "Bywater",
    "Deephallow",
    "Dwaling",
    "Frogmorton",
    "Gamwich",
    "Great Smials",
    "Greenholm",
    "Hardbottle",
    "Hobbiton",
    "Little Delving",
    "Long Cleeve",
    "Longbottom",
    "Michel Delving",
    "Mugworth",
    "Needlehole",
    "Nobottle",
    "Oatbarton",
    "Overhill",
    "Pincup",
    "Quarry",
    "Rushey",
    "Scary",
    "Stock",
    "Tighfield",
    "Tookbank",
    "Tuckborough",
    "Underhill",
    "Undertowers",
    "Waymeet",
    "Whitfurrows",
    "Whitwell",
    "Willowbottom",
    "Woodhall",
];
